Repository fusioninventory/fusioninventory-for-glpi, pull requests merged in 2018-09, with the labels that each got.

#2619 WIP Use constants for GLPI min and max version
  setup.php
Labels: code factorization

#2610 Fix computer search options
  inc/computer.class.php
Labels: bug

#2640 Add COMMENTS support to softwares inventory
  inc/formatconvert.class.php
  phpunit/1_Unit/SoftwareUpdateTest.php
Labels: improvement
